export const routeMap = {
  "/dashboard": { title: "PI360 • Desktop Dashboard", sub: "Command Center" },
  "/referrals": { title: "PI360 • Referrals", sub: "Manage patient referrals" },
  "/referrals/new": { title: "PI360 • New Referral", sub: "Create a new patient referral" },
  "/cases": { title: "PI360 • Cases", sub: "View all cases" },
  "/schedule": { title: "PI360 • Schedule", sub: "Appointments & visits" },
  "/messages": { title: "PI360 • Messages", sub: "Inbox & Compose" },
  "/messages/compose": { title: "PI360 • Compose Message", sub: "Send a new message" },
  "/tasks": { title: "PI360 • Tasks", sub: "Manage tasks" },
  "/tasks/new": { title: "PI360 • New Task", sub: "Create a new task" },
  "/attorney": { title: "PI360 • Attorney Portal", sub: "Law firm info & cases" },
  "/discovery": { title: "PI360 • Discovery & Petitions", sub: "Track discovery requests" },
  "/analytics": { title: "PI360 • Analytics", sub: "KPIs & Insights" },
  "/admin": { title: "PI360 • Admin", sub: "Manage templates & settings" },
};
